### ISSUE TITLE
Static reference to local maven repo when compiled to native

### ISSUE THREAD

**Issue by tqvarnst** [quarkiverse/quarkus-maven-resolver#13]
It seems that the location of the local maven repository is statically stored in the image, but it should probably default to $HOME/.m2 or be possible to be overridden with environment variables. The details of this issue are captured in https://github.com/tqvarnst/rhbq-supported-extension-generator/issues/5 (private repo).

**Comment by aloubyansky** [comment]
It's the user home dir that is stored in the image and then it's used to resolve user settings and the maven local repo dir. `-Dmaven.repo.local=path` can be used on the command line to configure the right location.
This PR will fix the issue https://github.com/quarkusio/quarkus/pull/23972

**Comment by aloubyansky** [comment]
Should have been fixed in the previous release.
