### ISSUE TITLE
addRemoteRep ?

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-maven-resolver#9]
can only add a remote repo by calling getRemoteRepositories().add() or addRemoteRepositories with list..not individual.

**Comment by aloubyansky** [comment]
Didn't notice there were issues logged. I just added support for `quarkus.maven-resolver.repositories.<repo-id>=<repo-url>`. It's very basic, it doesn't allow configuring anything more currently.

**Comment by aloubyansky** [comment]
I'll close this one, please re-open if you need more options. Thanks.
